# coding: utf-8

"""
    UE Dataset API

    API definition for UE activity dataset.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from openapi_client.models.app_interval import AppInterval
from typing import Optional, Set
from typing_extensions import Self

class UE(BaseModel):
    """
    UE
    """ # noqa: E501
    id: Optional[StrictInt] = Field(default=None, description="Unique identifier for the UE", alias="Id")
    imsi: Optional[StrictStr] = Field(default=None, description="IMSI for the UE", alias="IMSI")
    arrival_time: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Time when the UE arrives in the network", alias="Arrival_time")
    applications: Optional[List[AppInterval]] = Field(default=None, description="List of applications with start and end times", alias="Applications")
    leave_time: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Time when the UE leaves the network", alias="Leave_time")
    __properties: ClassVar[List[str]] = ["Id", "IMSI", "Arrival_time", "Applications", "Leave_time"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of UE from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in applications (list)
        _items = []
        if self.applications:
            for _item_applications in self.applications:
                if _item_applications:
                    _items.append(_item_applications.to_dict())
            _dict['Applications'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of UE from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "Id": obj.get("Id"),
            "IMSI": obj.get("IMSI"),
            "Arrival_time": obj.get("Arrival_time"),
            "Applications": [AppInterval.from_dict(_item) for _item in obj["Applications"]] if obj.get("Applications") is not None else None,
            "Leave_time": obj.get("Leave_time")
        })
        return _obj


